### ISSUE TITLE
barrel explosion

### ISSUE THREAD

**Issue by marcinmarcinmarcin** [jekyllgrim/Beautiful-Doom#12]
is it possible to add option to choose between enhanced and vanilla barrel explosion?

**Comment by 3saster** [comment]
I second this. Certain maps will stack barrels to create a more powerful explosion (for example, Deus Vult II MAP01, where the cacodemons are), but this can cause extreme lag in Beautiful Doom. Alternatively (or additionally), an automatic check could occur when the level starts to look for multiple barrels and correct this somehow.

**Comment by jekyllgrim** [comment]
A big part of the barrel explosion effects are controled by Debris option, so if you turn them off, the explosion doesn't cause slowdowns. Also, in the current repo the barrel hasn't been exported to ZScript yet, so there hasn't been a round of optimization. When it's done, the explosion won't be resource-intensive.
