### ISSUE TITLE
Neural 2x upscaled sprites available for Beautiful Doom

### ISSUE THREAD

**Issue by r6d2** [jekyllgrim/Beautiful-Doom#15]
Hi, Jekyll!

I've been working on a **Neural Upscaled sprite set** for your mod. I basically upscaled most of the sprites with `Waifu2x` and then run an `ImageMagick` script on them to remove some artifacts.

I have fully completed weapons and monsters, with more to come. Everything new resides on the Hires folder so it does not conflict with anything you've done so far.

Would you be interested in trying these out? If you grant me contributor permission I can create a pull request.

Let me know, best regards!

**Comment by jekyllgrim** [comment]
Hi there! I appreciate all the work, and it's a neat idea. However, I personally have always disliked neural upscale, it doesn't look the way I'd like the mod to look, and I don't think it's worth the increased filesize (which is already quite large). I'd be perfectly OK if you made it into an addon that can be run alongside Beautiful Doom, but I'm not planning to do neural upscale a part of the core mod. Sorry!

If you do finish it as an add-on, I'll post the link somewhere (in the mod thread on ZDoom probably).

**Comment by r4** [comment]
@r6d2 Have you made any progress on this potential add-on? I'd love to give it a run and provide feedback. I'm a fan of the NeuralUpscale2x mod.
