### ISSUE TITLE
Add an option to disable weapon reloading

### ISSUE THREAD

**Issue by electricmessiah** [jekyllgrim/Beautiful-Doom#16]
This should definitely be an option and not a default behavior. If the mod's intent is to beautify the original Doom, then all features that add additional functionality should be optional. IMO, reloading is cool when you want it, but when you want to burn through levels old-school style it just gets in the way and disrupts the flow.

**Comment by jekyllgrim** [comment]
Reloading _is_ optional. It's a feature of the Modern Guns only which are specifically designed and balanced to have reloads. Vanilla and Enhanced weapon sets don't have reload. See Options > Beautiful Doom Settings.
