### ISSUE TITLE
Stalagmite issue

### ISSUE THREAD

**Issue by micheledamato** [jekyllgrim/Beautiful-Doom#17]
Hi, the modern super shotgun sprite replaces the stalagmite sprite.

![Screenshot_Doom_20200103_214641](https://user-images.githubusercontent.com/15909982/71748386-ad7cad00-2e72-11ea-8b82-cda5ef94404d.jpg)

![immagine](https://user-images.githubusercontent.com/15909982/71748265-419a4480-2e72-11ea-9c57-56d021759011.png)

Thanks.

**Comment by jekyllgrim** [comment]
Just pushed an update with a fix, thanks.
