### ISSUE TITLE
Monster Transparency Issues

### ISSUE THREAD

**Issue by Samarai** [jekyllgrim/Beautiful-Doom#18]
https://imgur.com/a/s3wUphS

I'm playing Going Down with BD and generally having a fun time, but I'm seeing monster sprites randomly become transparent, rendering things behind them as if they were in front of them. Screenshots of the issue are in the album above. My GZDoom version is the latest stable release (4.3.3) and I can provide other technical details if required.

**Comment by 3saster** [comment]
[This might be an engine bug](https://forum.zdoom.org/viewtopic.php?f=7&t=66792). It was supposed to be fixed, but it might have resurfaced, or not been fixed properly. I'd probably make a bug report on the ZDoom forums, this doesn't look like a mod bug to me.

(btw, your imgur link is not linked correctly)

**Comment by jekyllgrim** [comment]
We'll try to catch it during testing, thanks for reporting.
