### ISSUE TITLE
Script error, Material definition refers nonexistent texture, Ultimate Doom

### ISSUE THREAD

**Issue by Aszarsha** [jekyllgrim/Beautiful-Doom#19]
Hi,

With both the 27.01.2020 release, as well as master branch from 2020-03-17 (commit f6a61c), I get the following console errors when starting the game:

Script error, "Beautiful-Doom-20200317.zip:gldefs.tex" line 16:
Material definition refers nonexistent texture 'DBRAIN1'
Script error, "Beautiful-Doom-20200317.zip:gldefs.tex" line 21:
Material definition refers nonexistent texture 'SFALL1'
Script error, "Beautiful-Doom-20200317.zip:gldefs.tex" line 27:
Material definition refers nonexistent texture 'BFALL1'

The mod runs ok as far as I can tell (and I absolutely love it, particularly the modern weapons which feel great !).
Using gzdoom 4.3.3 over Ultimate Doom, Steam release. Maybe doom2.wad is actually required even to play Doom1?

**Comment by jekyllgrim** [comment]
Won't cause any issues, it's just an irrelevant error report that can't be silenced. I'm not yet sure if there's a way to make it not appear, though.

**Comment by 3saster** [comment]
> Won't cause any issues, it's just an irrelevant error report that can't be silenced. I'm not yet sure if there's a way to make it not appear, though.

Can be fixed easily actually. Since those definitions are needed for Doom 2 only, use lump filtering, and make `filter/doom.id.doom2/GLDEFS.tex`. Move the offending sections from the global `GLDEFS.tex` to the filtered one we just made. Then, it will only attempt to load the "problematic" textures for Doom 2, and ignore them for Doom 1.

**Comment by jekyllgrim** [comment]
Actually, the definitions are not only referring to existing Doom textures but also to some texture names that are common used in PWADs but don't exist in vanilla Doom, like FWALL. I know this might be overengineering it a bit, but  those really are common textures. And there's no way to filter those out. I don't know why we don't have an **optional** keyword for material definitions, but for now it is how it is. Maybe I'll remove those extra definitions.
