### ISSUE TITLE
Minimal HUD doesn't show keys

### ISSUE THREAD

**Issue by swc132994** [jekyllgrim/Beautiful-Doom#21]
Not sure if this is intended but using the minimal HUD does not show any keys picked up.

![2020-04-24_16-10-10](https://user-images.githubusercontent.com/10770202/80180873-0d2bdd80-8647-11ea-9947-7f94df3139a4.png)

**Comment by 3saster** [comment]
Take a look in the top right corner :P

**Comment by swc132994** [comment]
Whoops. Completely missed that, never thought to look on the top. My Apologies!
