### ISSUE TITLE
Spider Mastermind Issue

### ISSUE THREAD

**Issue by AlucedIcen** [jekyllgrim/Beautiful-Doom#22]
I'm playing the regular Doom 2 campaign, and i just reached map20 "Gotcha!".
In this map you are able to make a cyberdemon and a Spider Mastermind infight with each other.
However, with Beautiful Doom monster enabled, the Spider Mastermind does not mind the cyberdemon attacking it and will keep shooting the player. Even if the player moves out of sight, the Spider will simply ignore the Cyberdemon.
I'm using the 27.01.2020 pre-7 release.

**Comment by jekyllgrim** [comment]
Thank you, this is fixed as of today in the github version and will be included in the next release.
