### ISSUE TITLE
Fix for potential GZDoom VM execution array error

### ISSUE THREAD

**Issue by Frozsoul2019** [jekyllgrim/Beautiful-Doom#24]
If you run GZDoom 4.4.0 with the current development version of Beautiful Doom as well as any other addon file(s) that contain many textures, GZDoom can potentially stop loading with the error:
`VM execution aborted: array access out of bounds. Max.index = 894, current index = 894`

This error seems to occur because the while loop in line 564 of the addANIMDEFS function in bd_events.zc does not anticipate any add-on file(s) being loaded along with Beautiful Doom that may contain many other textures,  exceeding GZDoom's limits:
https://github.com/jekyllgrim/Beautiful-Doom/blob/a61d92907c509b299a8d3687af0c84654e586776/Z_BDoom/bd_events.zc#L564

The fix for this error is to slightly modify this line as follows:
`while( tokens[i] ~== "pic" && i < tokens.Size() && i < 890)`

**Comment by 3saster** [comment]
This is a lazy fix that pretty much just ignores past a certain number of tokens, I'd rather fix it properly. Can you provide a mod that causes this VM abort?

**Comment by Frozsoul2019** [comment]
Yes - this WAD file which contains many custom textures used for ObAddon (an Oblige add-on):
https://github.com/caligari87/ObAddon/blob/master/src/games/doom/data/ObAddon_Textures.wad

**Comment by jekyllgrim** [comment]
3saster made a PR with a fix and it's been pushed. Thanks!
