### ISSUE TITLE
There are still missing PlasmaRifle cooldown frame with black gloves 

### ISSUE THREAD

**Issue by EsDraft** [jekyllgrim/Beautiful-Doom#25]
I found this issues went  i using black gloves and I thought it is vanilla glove went it cooldown after fire. And i check files with Slade3 and I found it's only have vanilla glove. This is not bug it's just a missing frame.

**Comment by jekyllgrim** [comment]
Fixed in [fd051ba](https://github.com/jekyllgrim/Beautiful-Doom/commit/fd051ba6adbbb68e6db0c9f0b21a9049c1b4e502)
