### ISSUE TITLE
Enhanced SSG secondary fire issue

### ISSUE THREAD

**Issue by Qinus** [jekyllgrim/Beautiful-Doom#28]
Depleting a clip with secondary fire then holding secondary fire while reloading will shoot both barrels once it is reloaded and consume 1 ammo

**Comment by jekyllgrim** [comment]
Pushed a commit, this should be fixed now. Thanks!

**Comment by Qinus** [comment]
That fixed the issue! But now if you secondary -> primary fire it will will use 3 ammo

**Comment by jekyllgrim** [comment]
Pushed another commit, this should fix it, hopefully :)
