### ISSUE TITLE
Some modern weapons stay on-screen after dying

### ISSUE THREAD

**Issue by Qinus** [jekyllgrim/Beautiful-Doom#30]
- While chainsaw is on and attack is held
- Plasma Rifle while idle and being cooled down
- While BFG is idle or charging up
- Kick sprite
- Rocket launcher while reloading

**Comment by jekyllgrim** [comment]
This one might be a bit trickier, I'll look into it. Thanks!

**Comment by Qinus** [comment]
Latest commit fixed it, nice work

**Comment by Qinus** [comment]
Actually one minor thing, charged BFG shot stays on screen
