### ISSUE TITLE
Flies buzzing sounds weird

### ISSUE THREAD

**Issue by swc132994** [jekyllgrim/Beautiful-Doom#35]
Just wanted to say I am really enjoying the changes you have made to the development version of the mod.  Its the development version ending in aa56bac.

I just wanted to flag up this issue when a body is left for a while it will generate flies. The only problem is the buzzing sound, sounds weird and not like buzzing at all.

I have attached a zipped small video:
[Hydroelectric Plant - Freedoom_ Phase 2 2020-08-03 14-07-21.zip](https://github.com/jekyllgrim/Beautiful-Doom/files/5013799/Hydroelectric.Plant.-.Freedoom_.Phase.2.2020-08-03.14-07-21.zip)

Best regards,
swc132994

**Comment by jekyllgrim** [comment]
Which port, version, map and other mods (if any) are you using?

**Comment by swc132994** [comment]
Hi,
I am using GZDoom 4.4.2 along with Freedoom-0.12.1 phase 2. I did run it with a self made DEHACKED language lump patch.pk3 to override the forced freedoom messages and a self made Aubrey Hodges PSX music pack.pk3. However I just ran Beautiful doom-aa56bac again in Wadsmooshed Doom without any other mods and I am hearing the same sound from the flies over the bodies.

Best regards,
swc132994

**Comment by jekyllgrim** [comment]
Foudn the bug, will be fished in the next commit. Thanks!

**Comment by swc132994** [comment]
Many Thanks.

**Comment by jekyllgrim** [comment]
This should be fixed by now btw.

**Comment by swc132994** [comment]
Thanks for the update. However the fly sound still remains the same as per the video. Can this issue be reopened?

**Comment by jekyllgrim** [comment]
I'll ivestigate this further...

**Comment by jekyllgrim** [comment]
Finally fixed :D

**Comment by swc132994** [comment]
Hi Jekyllgrim

Apologies for the late reply. I don't check my messages as often as I should.
I have just tested the latest build and indeed this sound bug is fixed. Thank you very much :)

Best regards,
swc132994
