### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by HaskiHero** [jekyllgrim/Beautiful-Doom#38]
I played this mod using ZDL and launch it on GZDoom version 4.2.2. The game is normal but after a few minutes the game will crash and said "FATAL error".

Note: I also want to ask. Why this mod isn't in LZDoom?

**Comment by jekyllgrim** [comment]
A crash is an unhandled exception, and if that occurs, that's a problem with GZDoom, not with a mod. GZDoom should always be able to provide an actual error report when it runs into an issue.

GZDoom 4.2.2 is outdated and is not supported by the mod. The repository build requires at least 4.4.0. The readme describes how to download the repository.

LZDoom is a version of GZDoom intended for older hardware. It might be supported, I never tested with it and I don't know how much up-to-date LZDoom is compared to the current GZDoom.
