### ISSUE TITLE
Memory leak on Beautiful Doom aa56bac, GZDoom 4.4.2

### ISSUE THREAD

**Issue by swc132994** [jekyllgrim/Beautiful-Doom#39]
Whilst playing Beautiful I noticed from time to time it would crash. I later noticed this was due to my computer running out of memory (computer has 16Gb). On large maps the memory consumption becomes worse (probably due many dead monsters, approx. 200) and the memory keeps ticking up even when inactive but unpaused at around 50Mb a second (pausing the game will stop the memory use climbing up). I used the clear debris and this help with the memory but memory will still keep ticking up but more slowly.

I unchecked other mods and ran it with just Beautiful doom just in case it was another mod causing the memory issue.

Running:
Windows 10 64 Bit, 2004 build.
GZDoom 4.4.2 64 Bit
Freedoom 12.1 Phase 2
Beautiful doom-aa56bac

Best regards,
swc132994

**Comment by 3saster** [comment]
This is an issue on GZDoom's part, not Beautiful Doom's; there is a known memory leak in 4.4.2. Thankfully, it is patched in the [devbuilds](https://devbuilds.drdteam.org/gzdoom/); any version 4.5pre-52 or newer fixes the memory leak. Truthfully, this is a severe enough issue that I would have thought 4.4.3 would have released with the fix, but it seems not. Until the next GZDoom stable releases, use a devbuild for now.

**Comment by swc132994** [comment]
Hi 3saster

Thanks for the quick reply.
I have just tried out the latest GZDoom Dev build. Memory leak has stopped.

**Comment by jekyllgrim** [comment]
Thanks, 3saster.
