### ISSUE TITLE
Berserker Pack

### ISSUE THREAD

**Issue by Beezle9891** [jekyllgrim/Beautiful-Doom#4]
After these latest commits, berserker packs do not seem to work after picking them up with the Enhanced Weapon set. They still give 100% though. Loaded with SimpleUIAddons and Immerse 104 mods.
![screenshot_doom_20190111_222617](https://user-images.githubusercontent.com/45604754/51070129-9523da80-15f0-11e9-8c58-a8c159b43d87.png)

**Comment by 3saster** [comment]
Reason why is because [these lines](https://github.com/jekyllgrim/Beautiful-Doom/blob/a9367210fca61d8d223de912badb0496191630ec/Z_BDoom/w_fist.zc#L1030) have been commented out. Trivial to correct, I will push a fix.

**Comment by jekyllgrim** [comment]
Fixed. Thanks guys!
