### ISSUE TITLE
graphic bug with Beautiful-Doom + steve_flashlight_2018.02.12

### ISSUE THREAD

**Issue by marcinmarcinmarcin** [jekyllgrim/Beautiful-Doom#44]
flashlight off
![latarka](https://user-images.githubusercontent.com/19805466/106130763-0eec7980-6162-11eb-9abe-4f0092c248be.jpg)
flashlight on
![latarka1](https://user-images.githubusercontent.com/19805466/106130771-11e76a00-6162-11eb-9ea7-a0fda023c64a.jpg)
flashlight on
![latarka3](https://user-images.githubusercontent.com/19805466/106130774-12800080-6162-11eb-90d4-394d0242937f.jpg)
flashlight off
![latarka4](https://user-images.githubusercontent.com/19805466/106130778-13b12d80-6162-11eb-8c2f-500539caadeb.jpg)

**Comment by jekyllgrim** [comment]
Blood textures have materials (normal and specular maps) attached, and they will reflect dynamic lights. This is a proper reflection.
