### ISSUE TITLE
Newest release not functioning on gzdoom 4.5.0

### ISSUE THREAD

**Issue by PlanetOrca** [jekyllgrim/Beautiful-Doom#45]
The most recent release doesn't function on gzdoom v4.5.0.
It gives an error that says it attempted to write at address 0

**Comment by 5ky1ar** [comment]
i was literally about to make the same issue, for me, it happens when i use a teleporter

**Comment by PlanetOrca** [comment]
> i was literally about to make the same issue

It just straight-up doesn't work for me. However, there is another issue which is currently closed which should be the exact same issues, I recommend you go check it out
