### ISSUE TITLE
game boots me out when I use a teleporter

### ISSUE THREAD

**Issue by 5ky1ar** [jekyllgrim/Beautiful-Doom#46]
the game boots me out when I use a teleporter with this error message in the console

```
Attempt to spawn an instance of abstract actor class BD_BaseFlare
VM execution aborted: tried to read from address zero.
Called from Actor.A_SetScale at gzdoom.pk3:zscript/actors/actor.zs
Called from BD_TeleportFog.PostBeginPlay at BeautifulDoom200612.pk3:z_bdoom/o_misc.zc, line 24
```

# OS Info
Edition: Windows 10 Home  
Version: 20H2  
OS build: 19042.804  
Experience: Windows Feature Experience Pack 120.2212.551.0  

# GZDoom Version
GZDoom g4.5.0

# Game/IWAD
Doom 2

**Comment by jekyllgrim** [comment]
This issue was fixed a few commits ago. Follow [the instructions on the readme page](https://github.com/jekyllgrim/Beautiful-Doom#how-to-play-the-latest-release) to play the latest version of the mod. (Note, you may not be able to download your save.)
