### ISSUE TITLE
Error: ATTEMPT TO SPAWN AN INSTANCE OF ABSTRACT ACTOR CLASS BD_BASEFLARE

### ISSUE THREAD

**Issue by megaboyx90** [jekyllgrim/Beautiful-Doom#48]
GZDoom 4.5.0
Other Mods: None
Error: ATTEMPT TO SPAWN AN INSTANCE OF ABSTRACT ACTOR CLASS BD_BASEFLARE
Description: 
This happens when an archvile does his flame attack at any given point in time.
Very annoying and it fills the message prompt, very good mod but this bug annoyed me a bit
![image](https://user-images.githubusercontent.com/45728868/111671243-c018a300-87e6-11eb-8eff-ce8422705cea.png)

**Comment by jekyllgrim** [comment]
Fixed a while ago, please play a dev build: https://github.com/jekyllgrim/Beautiful-Doom#how-to-play-the-freshest-dev-build
