### ISSUE TITLE
GZDoom 4.6.0 doesn't load Beautiful Doom

### ISSUE THREAD

**Issue by jankespro12** [jekyllgrim/Beautiful-Doom#51]
I tried to load Beautiful Doom in GZDoom 4.6.0 but it doesn't work and i get this message:

Script error, "fdhud.pk3:fontdefs" line 14:
STTSLASH: Unable to find texture in font definition for STATUSFONT
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
Beautiful_Doom_710.pk3:z_bdoom/bd_menu.zc, line 43: Function isGrayed attempts to override parent function without 'override' qualifier
1 errors, 0 warnings while compiling Beautiful_Doom_710.pk3:zscript.zc

**Comment by jekyllgrim** [comment]
Yes, that is a known issue. I recently updated the description of 7.1.0 release to reflect that. Please refer to [How to play the freshest dev build](https://github.com/jekyllgrim/Beautiful-Doom#how-to-play-the-freshest-dev-build) to get a build where this is fixed.

**Comment by jekyllgrim** [comment]
There's also a [7.1.5 release](https://github.com/jekyllgrim/Beautiful-Doom/releases/tag/7.1.5) now contains the fix.
