### ISSUE TITLE
Super Shotgun has alt-fire on vanilla weapons

### ISSUE THREAD

**Issue by JohnKirk1337** [jekyllgrim/Beautiful-Doom#54]
**GZDoom** v4.6.1
**Map:** any
**Other mods:** None
**Error:** None
**Description:** Even with Player Weapons set to Vanilla, the super-shotgun can alt-fire if you press it _right after reloading_.

**Comment by jekyllgrim** [comment]
Thanks for pointing out this oversight. Fixed in 93a8f4e8cbd27f6f952ce8ce127f75b4f0f5d0e2. You can wait for the next stable release or [download the freshest dev build](https://github.com/jekyllgrim/Beautiful-Doom#how-to-play-the-freshest-dev-build) to have the fix in your game.
