### ISSUE TITLE
Unknown Textures ? 

### ISSUE THREAD

**Issue by G-MOB72** [jekyllgrim/Beautiful-Doom#56]
When I Loaded into E1M1 [This only happens with Doom I/UD] It showed a msg 'Unknown Texture SP_Dude'  For of em.
I am not using any other mods or add-ons. 

I'm using the Latest version of GZDoom | 4.7.1 

![Screenshot_1](https://user-images.githubusercontent.com/92063554/170873123-fc3c4db0-4507-428a-876a-e972bfbd94ec.png)

**Comment by jekyllgrim** [comment]
This is a known issue (listead on the [Notion development board](https://www.notion.so/Check-if-I-can-make-SP_DUDE-textures-optional-91b280913a30495497d7ced7b175d2b6)). I've not yet looked into a possible fix, but in any case, it will not cause any practical issues in the game.

**Comment by jekyllgrim** [comment]
Fixed in 663cbe4eaa10b96700e7d2f114f43ce0e27b523e

**Comment by Sol1vaN** [comment]
sorry for reopen this
but now in uzdoom 4.14.3 this problem come back

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/bb8a2419-e16d-4b5b-9c77-8ac2e61f9783" />

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/2d001aed-39e1-42d2-a140-f2bac579aeb7" />
