### ISSUE TITLE
Modern Weapons can't trigger shootable triggers in maps

### ISSUE THREAD

**Issue by ZeintheDev** [jekyllgrim/Beautiful-Doom#58]
GZDoom g4.8.2
Map: SIGIL E5M1, no deathmatch
Other mods: none
Error: no error message
Description:
Sigil likes to make use of shootable switches, but with modern weapon those just don't work.
Suggested solution:  It might be that you're using projectile even tho it doesn't really look like it. If that's the case, just do a quick hitscan that doesn't do any damage.

**Comment by jekyllgrim** [comment]
Fixed in 99b682b31121e0c3a1b5d01657b09572c1195ea1
Modern weapons' bullet attacks will now fire an invisible hitscan at player's attack height
