### ISSUE TITLE
splash sounds create volume spike

### ISSUE THREAD

**Issue by br4nnigan** [jekyllgrim/Beautiful-Doom#59]
with the vanilla blood particle setting (enhanced blood: off), the blood particles create a splash sound when falling into liquid. This shouldn't be, but it's not an actual problem. An actual problem is when using for example the super shotgun, and many blood particles hit the floor at the same time the volume stacks up and creates a nasty spike louder than any other sound

this is also a problem when you just shoot into the water (unrelated to the enhanced blood setting): many splash sounds will play at the same time and create a very loud sound

it's very annoying unfortunately.

I mean this might just be how GZDoom handles sound, but then maybe create a setting to disable those splash sounds, or I'll just remove it from the files myself.

**Comment by jekyllgrim** [comment]
This should be fixed in 53974b963c5f85c904808e7069a6b2d91bb5dd00
I limited the simultaneous splash sounds to 2.

**Comment by br4nnigan** [comment]
dude that is awesome, it works! finally
