### ISSUE TITLE
Autoaim isnt working correctly

### ISSUE THREAD

**Issue by Arcevalis** [jekyllgrim/Beautiful-Doom#62]
GZDoom: 4.10
Map: Tested with NOVA mappack - MAP04
Other mods: No Other Mods loaded
Error: N/A
Description: Mouselook disabled. Autoaim set to "35" or always.

https://user-images.githubusercontent.com/29128256/216791276-f5ee94a5-306d-4f8a-a666-3e91de8d4ecf.mp4

Autoaim seems to shoot above or below the enemy depending if the enemy is higher or lower than the player.
Bug happens the best using the shotgun

**Comment by jekyllgrim** [comment]
Fixed in a8f45d973ed19f72e6b2b25f987c1e608e77bb66
Thank you
