### ISSUE TITLE
Tapfiring autoaim for pistol and chaingun is not working

### ISSUE THREAD

**Issue by Arcevalis** [jekyllgrim/Beautiful-Doom#63]
GZDoom: 4.10
Map: NOVA - MAP04
Other mods: No other mods 
Error: N/A
Description: 

Tapfire Autoaim for these weapons are not functioning
Pistol: 

https://user-images.githubusercontent.com/29128256/216795376-aa91f0dc-e6c3-433a-8bf9-f24e7fdbb09f.mp4

Chaingun: 

https://user-images.githubusercontent.com/29128256/216795377-3e7c4a91-2ac5-4497-9146-b9fde95fbe0f.mp4

**Comment by Arcevalis** [comment]
Now that I think about it, this possibly can happen with any weapon but its weird. If you tapfire, dont hold, with the shotgun its projectiles will go to multiple different enemies? Need to test more for this but worth checking out

**Comment by jekyllgrim** [comment]
Yup, oversight on my part. This should be fixednow  in c4d791b
