### ISSUE TITLE
[Suggestion] Option for slower reloads when using the modern weapon set

### ISSUE THREAD

**Issue by FistsAkimbo** [jekyllgrim/Beautiful-Doom#65]
The modern weapon set is phenomenal and is basically what I was looking for to no avail for some time; a general polished up reload-focused set of the classic weapons. The extra firepower offered in the set feels just right, but I was wondering if there could be an option to slow down the reload speeds for at least the ballistic weapons (so the energy weapons could stand out in greater contrast of not requiring reloads, and generally being capable of more sustained fire.) Often times it feels overpowered when the reload is brutal doom tier fast, making me sometimes opt to not use it on milder maps, when it's otherwise ideal to me. 

If not, I understand, and could likely just double up the frames myself, but as an option it could be available for everyone.

**Comment by jekyllgrim** [comment]
Thank you for the suggestion, but I think it's very niche, and I'm extremely wary of feature creep, so I try to avoid adding separate options for every possible feature. Feel free to create a personal addon for this.

**Comment by FistsAkimbo** [comment]
Then what's the best method to change that? Adding additional frames to the reload state? Which states in particular?

**Comment by jekyllgrim** [comment]
Yes, the reload animation is usually in the **Reload** state sequence. Sometimes it may also be the **ReloadDo** state sequence that is entered from Reload. You can extend the duration of any frame that isn't 0. For example, this is the Modern Pistol reload sequence:
```csharp
	Reload:
		TNT1 A 0 {
			If(!A_CheckAmmo()) {
				invoker.wasempty = true;	//this defines whether to show dry reload sprites or regular ones
				BD_SetSprite("PIME","QIME");
			}
			else
				BD_SetSprite("PIMR","QIMR");
		}
		#### ABCD 1;
		#### # 0 A_StartSound("Mweapons/pistol/clipout",slot:CHAN_5);
		#### EFG 2 A_WeaponOffset(-0.3,1,WOF_ADD);
		#### DDDD 3 A_WeaponOffset(-0.2,0.25,WOF_ADD);
		#### HI 2 A_WeaponOffset(2.55,-2,WOF_ADD);
		#### # 0 {
			A_StartSound("Mweapons/pistol/clipin",slot:CHAN_5);
			if (!invoker.wasempty)
				BD_Reload();
		}
		#### JK 2;
		#### L 5 ;
		TNT1 A 0 {
			If(!invoker.wasempty)
				return ResolveState("ReloadEnd");
			return ResolveState(null);	//if reload was dry, move the slide
		}
		TNT1 A 0 {
			A_StartSound("Mweapons/pistol/cock");
			BD_SetSprite("PIME","QIME");
		}
		#### MNOOOO 1;
		TNT1 A 0 BD_Reload();
```
You could edit the ABCD or EFG or DDDD and such, for example increasing their tic duration by one. For example, this would increase the total duration by 7 tics (each frame in ABCD is longer and each frame in EFG is longer):
```csharp
		#### ABCD 2; //2 instead of 1
		#### # 0 A_StartSound("Mweapons/pistol/clipout",slot:CHAN_5);
		#### EFG 3 A_WeaponOffset(-0.3,1,WOF_ADD); //3 instead of 2
		#### DDDD 3 A_WeaponOffset(-0.2,0.25,WOF_ADD);
		#### HI 2 A_WeaponOffset(2.55,-2,WOF_ADD);
```

**Comment by FistsAkimbo** [comment]
Thanks for the example, this specific sort of thing was something I wanted more clear info on, as I've messed around with frame 'lifespan' in the past with -1 and by extending frames in the letter field, but I wasn't sure if there was an optimal way of doing it. Now I see it's like a call multiplier.
