### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by PopeRigby** [jekyllgrim/Beautiful-Doom#8]
- Make the assault rifle have an option for either toggle aim or hold to aim (most mods that have ADS don't let you hold to aim, and it can be a tad annoying).
- Make the sights come all the way up to the center of your screen and have it disable the crosshair (if you have it enabled) when you aim.
- Move the credits menu below the settings menu, for easier access to the settings.
- Make the plasma rifle file faster. One of the best things about the plasma rifle was its ROF. If you need to, nerf its damage but I think it's important that the plasma rifle fires fast.
- Make the plasma rifle fire more orb-shaped [projectiles](https://imgur.com/a/QmONBlC), instead of the [beam-shaped](https://imgur.com/8fMcoDa) ones. In-fact, the way you have it in the vanilla weapons is much better in my opinion
- Make it so you pump the shotgun all the way up like [this](https://imgur.com/fL2jSZV), instead of [this](https://imgur.com/s4P5SFK).
- Make the SSG have more kickback and recoil to make it feel more powerful.
- Maybe have the pistol reload a bit more pronounced and show your hands more. Same thing with the SSG and the rocket launcher.
- Have the assault rifle use different ammo from the pistol. Some people might not like this so maybe have an option.
- See if you can use some of the sounds from [Sound Caulking](https://www.doomworld.com/forum/topic/71133-sound-caulking-now-on-idgames/). The ones for the lost souls in particular would be useful because lost souls don't sound any different from pinkies.

I could help you, if I knew what tools you were using to make the mod. Is there a contribution guide?

**Comment by marcinmarcinmarcin** [comment]
and add flashlight

**Comment by jekyllgrim** [comment]
reviewed and discussed
